name       : wol
version    : 0.7.1
release    : 1
source     :
    - https://downloads.sourceforge.net/ahh/wol-0.7.1.tar.gz : e0086c9b9811df2bdf763ec9016dfb1bcb7dba9fa6d7858725b0929069a12622
license    : GPL-2.0
component  : network.util
summary    : Wake On Lan client
description: |
    This is wol, the Wake On Lan client. It wakes up magic packet compliant
    machines such as boxes with wake-on-lan ethernet-cards. Some workstations
    provides SecureON which extends wake-on-lan with a password. This feature
    is also provided by wol.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
